In [1]:
import torch

In [2]:
torch.__version__

'2.5.1+cpu'

# Tensors

## 1. Creating Tensors

In [3]:
# scalar - tensor with zero dimension
tensor0 = torch.tensor(1)
tensor0

tensor(1)

In [4]:
tensor0.ndim

0

In [5]:
# vector - tensor with one dimension
tensor1 = torch.tensor([6, 8, 0, 1, 2])

In [6]:
# matrix - tensor with two dimensions
tensor2 = torch.tensor(([0, 1, 7], [4, 2, 4]))

In [7]:
# Dimension and shape of a tensor
print(f'Vector:\n {tensor1}\t No. of dimensions: {tensor1.ndim}\t Shape: {tensor1.shape}\n')
print(f'Matrix:\n {tensor2}\t No. of dimensions: {tensor2.ndim}\t Shape: {tensor2.size()}\n')

Vector:
 tensor([6, 8, 0, 1, 2])	 No. of dimensions: 1	 Shape: torch.Size([5])

Matrix:
 tensor([[0, 1, 7],
        [4, 2, 4]])	 No. of dimensions: 2	 Shape: torch.Size([2, 3])



In [8]:
# Alternate ways
size = (3, 4)
tensor4 = torch.empty(size)
tensor4

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [9]:
tensor5 = torch.rand(size)
tensor5

tensor([[0.0405, 0.3245, 0.3879, 0.1710],
        [0.7780, 0.2156, 0.5347, 0.7690],
        [0.7084, 0.6942, 0.6276, 0.7682]])

In [10]:
tensor6 = torch.zeros(size)
tensor6

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [11]:
tensor7 = torch.ones(size)
tensor7

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [12]:
# Check the datatype of a tensor
tensor4 = torch.rand(1,2)
print(tensor4)
tensor4.dtype

tensor([[0.8331, 0.1397]])


torch.float32

In [13]:
# Create a tensor with a specific datatype
tensor5 = torch.rand(1, 2, dtype = torch.float16)
print(tensor5)

tensor([[0.6919, 0.4316]], dtype=torch.float16)


In [14]:
# Changing the datatype of a tensor
tensor4.type(torch.double)

tensor([[0.8331, 0.1397]], dtype=torch.float64)

In [15]:
# Creating tensors from a numpy array
import numpy as np

example_array = np.array([[9, 3], [0, 4]])
tensor8 =torch.from_numpy(example_array)

tensor9 = torch.tensor(example_array)
print(example_array)
print(tensor8)
print(tensor9)

[[9 3]
 [0 4]]
tensor([[9, 3],
        [0, 4]], dtype=torch.int32)
tensor([[9, 3],
        [0, 4]], dtype=torch.int32)


In [16]:
example_array*= 3
print(example_array)
print(tensor8)
print(tensor9)

[[27  9]
 [ 0 12]]
tensor([[27,  9],
        [ 0, 12]], dtype=torch.int32)
tensor([[9, 3],
        [0, 4]], dtype=torch.int32)


In [17]:
# Crearing a tensor from another tensor

tensor10 = torch.ones_like(tensor8)
tensor10

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)

In [18]:
# Device configuration

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

tensor11 = torch.ones(3, 7).to(device)

tensor11 = torch.zeros(3, 7, device = device)

## 2. Accessing elements in a tensor

In [19]:
tensor2

tensor([[0, 1, 7],
        [4, 2, 4]])

In [20]:
tensor2.dim()

2

In [21]:
tensor2.size()

torch.Size([2, 3])

In [22]:
tensor2[0]

tensor([0, 1, 7])

In [23]:
tensor2[1, 0]

tensor(4)

In [24]:
# Slicing
tensor2[:, 2] # this will guive us all the rows and only column 2

tensor([7, 4])

In [25]:
tensor2[0, :] # this will give us only row 0 along with all columns 

tensor([0, 1, 7])

## 3. Basic Tensor Operations

In [26]:
tensor12 = torch.ones(2, 3)
tensor13 = torch.rand(2, 3)

print(tensor12)
print(tensor13)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.2476, 0.0938, 0.3004],
        [0.7827, 0.1378, 0.6697]])


In [27]:
# Elementwise addition
tensor14 = tensor12 + tensor13
# torch.add(tensor12, tensor13)
print(tensor14)

# Elementwise subtraction
tensor15 = tensor12 - tensor13
# torch.sub(tensor12, tensor13)
print(tensor15)

# Elementwise multiplication
tensor16 = tensor12 * tensor13
# torch.mul(tensor12, tensor13)
print(tensor16)

# Elementwise division
tensor17 = tensor12 / tensor12
# torch.div(tensor12, tensor13)
print(tensor17)

tensor([[1.2476, 1.0938, 1.3004],
        [1.7827, 1.1378, 1.6697]])
tensor([[0.7524, 0.9062, 0.6996],
        [0.2173, 0.8622, 0.3303]])
tensor([[0.2476, 0.0938, 0.3004],
        [0.7827, 0.1378, 0.6697]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


## 4. Manipulating a Tensor

In [28]:
x = torch.randint(0, 3, (4, 5))
x

tensor([[1, 2, 1, 1, 0],
        [0, 0, 0, 1, 1],
        [1, 2, 0, 0, 2],
        [1, 1, 1, 2, 0]])

In [29]:
y = x.view(20)
z = x.view(-1, 10)

In [30]:
print(x.size(), y.size(), z.size())

torch.Size([4, 5]) torch.Size([20]) torch.Size([2, 10])


In [31]:
a = torch.arange(9)
a = a.reshape(3, 3)
a

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [32]:
b = torch.randint(0, 9, (3, 3)) ## torch.randint(low = 0, high, size)
b

tensor([[2, 4, 8],
        [2, 5, 3],
        [8, 3, 4]])

In [33]:
c = torch.cat((a, b), dim = 1)
c

tensor([[0, 1, 2, 2, 4, 8],
        [3, 4, 5, 2, 5, 3],
        [6, 7, 8, 8, 3, 4]])

In [34]:
d = torch.cat((a, b), dim = 0)
d

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8],
        [2, 4, 8],
        [2, 5, 3],
        [8, 3, 4]])

In [35]:
a

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [36]:
p = torch.randint(0, 9, (2, 3, 5))
p

tensor([[[1, 5, 5, 8, 0],
         [2, 8, 7, 8, 1],
         [5, 5, 6, 4, 0]],

        [[5, 8, 4, 8, 6],
         [2, 4, 0, 8, 7],
         [4, 5, 0, 3, 4]]])

In [37]:
p.sum()

tensor(133)

In [38]:
p.sum(dim = 0)

tensor([[ 6, 13,  9, 16,  6],
        [ 4, 12,  7, 16,  8],
        [ 9, 10,  6,  7,  4]])

In [40]:
p.sum(dim= 1)

tensor([[ 8, 18, 18, 20,  1],
        [11, 17,  4, 19, 17]])

In [41]:
p.sum(dim = 1).shape

torch.Size([2, 5])

# Autograd

In [43]:
import torch 

x = torch.tensor(2.0)
x.requires_grad, x.is_leaf

(False, True)

In [45]:
y = 3 * torch.sigmoid(x) + 5
y.requires_grad, y.is_leaf

(False, True)

In [48]:
import torch

x = torch.tensor(2.0, requires_grad = True)

x.requires_grad, x.is_leaf

(True, True)

In [49]:
y = 3 * torch.sigmoid(x) + 5
y

tensor(7.6424, grad_fn=<AddBackward0>)

In [50]:
y.requires_grad, y.is_leaf

(True, False)

In [51]:
print(x.grad_fn)

None


In [52]:
print(y.grad_fn)

In [53]:
print(x.grad)
y.backward()
print(x.grad) #dy/dx

None
tensor(0.3150)


In [54]:
# x.grad.zero_()
y = 3 * torch.sigmoid(x) + 5
y.backward()
x.grad

tensor(0.6300)

In [55]:
a = torch.rand(2, 5, requires_grad = True)
a

tensor([[0.5541, 0.5562, 0.6913, 0.7685, 0.0445],
        [0.5440, 0.4104, 0.6575, 0.2514, 0.8313]], requires_grad=True)

In [56]:
b = a * a + a + 5
b

tensor([[5.8611, 5.8656, 6.1692, 6.3591, 5.0464],
        [5.8400, 5.5789, 6.0898, 5.3146, 6.5224]], grad_fn=<AddBackward0>)

In [57]:
c = b.mean()
c

tensor(5.8647, grad_fn=<MeanBackward0>)

In [58]:
a.is_leaf, b.is_leaf, c.is_leaf

(True, False, False)

In [59]:
b.retain_grad()

In [60]:
print(a.grad) # Before gradient computation
c.backward()
print(a.grad) # After gradient computation dc/da

None
tensor([[0.2108, 0.2112, 0.2383, 0.2537, 0.1089],
        [0.2088, 0.1821, 0.2315, 0.1503, 0.2663]])


In [61]:
b.grad

tensor([[0.1000, 0.1000, 0.1000, 0.1000, 0.1000],
        [0.1000, 0.1000, 0.1000, 0.1000, 0.1000]])

# Gradient Descent

In [62]:
# Generate train data # y = 5 * x + 3
x = torch.linspace(0.0, 1.0, 15).reshape(15, 1)
w = torch.tensor([5])
b = torch.tensor([3])
y = w * x + b


In [64]:
# Parameter Initialization
w = torch.randn(size = (1, 1), requires_grad = True)
b = torch.randn(size = (1, 1), requires_grad = True)

def forward(x):
    return w * x + b

def loss(y, y_pred):
    return ((y_pred - y) ** 2).mean()

print('w: ', w)
print('b: ', b)

w:  tensor([[0.3893]], requires_grad=True)
b:  tensor([[0.8127]], requires_grad=True)


In [66]:
# Define hyper-parameters
learning_rate = 0.03
num_epochs = 180

#Train the model
for epoch in range(num_epochs):
    y_pred = forward(x)
    
    l = loss(y, y_pred)
    l.backward()
    
    with torch.no_grad():
        w -= learning_rate * w.grad
        b -= learning_rate * b.grad
        
    w.grad.zero_()
    b.grad.zero_()
    
    if (epoch + 1) % 10 == 0:
        print(f'epoch {epoch + 1}: w = {w.item() :.3f}, b = {b.item():.3f}, loss = {l.item():.3f}')

epoch 10: w = 1.741, b = 2.980, loss = 4.275
epoch 20: w = 2.260, b = 3.675, loss = 1.313
epoch 30: w = 2.551, b = 3.959, loss = 0.669
epoch 40: w = 2.735, b = 4.059, loss = 0.503
epoch 50: w = 2.870, b = 4.077, loss = 0.437
epoch 60: w = 2.980, b = 4.058, loss = 0.395
epoch 70: w = 3.076, b = 4.025, loss = 0.360
epoch 80: w = 3.164, b = 3.985, loss = 0.329
epoch 90: w = 3.246, b = 3.945, loss = 0.300
epoch 100: w = 3.324, b = 3.904, loss = 0.274
epoch 110: w = 3.399, b = 3.865, loss = 0.251
epoch 120: w = 3.469, b = 3.827, loss = 0.229
epoch 130: w = 3.537, b = 3.791, loss = 0.209
epoch 140: w = 3.601, b = 3.756, loss = 0.191
epoch 150: w = 3.663, b = 3.723, loss = 0.175
epoch 160: w = 3.722, b = 3.691, loss = 0.160
epoch 170: w = 3.778, b = 3.660, loss = 0.146
epoch 180: w = 3.832, b = 3.631, loss = 0.133


# Neural Networks

In [68]:
import torch
import torch.nn as nn
# import torch.nn.functional as F
import torch.optim as optim

from torchvision import datasets, transforms

In [69]:
print(dir(datasets))

['CIFAR10', 'CIFAR100', 'CLEVRClassification', 'CREStereo', 'Caltech101', 'Caltech256', 'CarlaStereo', 'CelebA', 'Cityscapes', 'CocoCaptions', 'CocoDetection', 'Country211', 'DTD', 'DatasetFolder', 'EMNIST', 'ETH3DStereo', 'EuroSAT', 'FER2013', 'FGVCAircraft', 'FakeData', 'FallingThingsStereo', 'FashionMNIST', 'Flickr30k', 'Flickr8k', 'Flowers102', 'FlyingChairs', 'FlyingThings3D', 'Food101', 'GTSRB', 'HD1K', 'HMDB51', 'INaturalist', 'ImageFolder', 'ImageNet', 'Imagenette', 'InStereo2k', 'KMNIST', 'Kinetics', 'Kitti', 'Kitti2012Stereo', 'Kitti2015Stereo', 'KittiFlow', 'LFWPairs', 'LFWPeople', 'LSUN', 'LSUNClass', 'MNIST', 'Middlebury2014Stereo', 'MovingMNIST', 'Omniglot', 'OxfordIIITPet', 'PCAM', 'PhotoTour', 'Places365', 'QMNIST', 'RenderedSST2', 'SBDataset', 'SBU', 'SEMEION', 'STL10', 'SUN397', 'SVHN', 'SceneFlowStereo', 'Sintel', 'SintelStereo', 'StanfordCars', 'UCF101', 'USPS', 'VOCDetection', 'VOCSegmentation', 'VisionDataset', 'WIDERFace', '__all__', '__builtins__', '__cached__',

In [70]:
# Hyper-parameters
hidden_size = 400
num_epochs = 8
batch_size = 32
learning_rate = 0.0001

In [71]:
# Load the MNIST dataset
train_dataset = datasets.MNIST(root = './data', train = True, download = True, transform = transforms.ToTensor())
test_dataset = datasets.MNIST(root = './data',train = False, download = True, transform = transforms.ToTensor())

Failed to download (trying next):
HTTP Error 404: Not Found



100%|█████████████████████████████████████████████████████████████████████████████| 9.91M/9.91M [00:03<00:00, 3.27MB/s]


Extracting ./data\MNIST\raw\train-images-idx3-ubyte.gz to ./data\MNIST\raw

Failed to download (trying next):
HTTP Error 404: Not Found



100%|██████████████████████████████████████████████████████████████████████████████| 28.9k/28.9k [00:00<00:00, 106kB/s]


Extracting ./data\MNIST\raw\train-labels-idx1-ubyte.gz to ./data\MNIST\raw

Failed to download (trying next):
HTTP Error 404: Not Found



100%|██████████████████████████████████████████████████████████████████████████████| 1.65M/1.65M [00:01<00:00, 847kB/s]


Extracting ./data\MNIST\raw\t10k-images-idx3-ubyte.gz to ./data\MNIST\raw

Failed to download (trying next):
HTTP Error 404: Not Found



100%|█████████████████████████████████████████████████████████████████████████████████████| 4.54k/4.54k [00:00<?, ?B/s]

Extracting ./data\MNIST\raw\t10k-labels-idx1-ubyte.gz to ./data\MNIST\raw



In [76]:
# Training Data
print(train_dataset.classes)
print(train_dataset.data.shape)
print(train_dataset.targets.shape)

['0 - zero', '1 - one', '2 - two', '3 - three', '4 - four', '5 - five', '6 - six', '7 - seven', '8 - eight', '9 - nine']
torch.Size([60000, 28, 28])
torch.Size([60000])
