In [1]:
import torch

In [2]:
torch.__version__

'2.5.1+cpu'

# Tensors

## 1. Creating Tensors

In [3]:
# scalar - tensor with zero dimension
tensor0 = torch.tensor(1)
tensor0

tensor(1)

In [4]:
tensor0.ndim

0

In [5]:
# vector - tensor with one dimension
tensor1 = torch.tensor([6, 8, 0, 1, 2])

In [6]:
# matrix - tensor with two dimensions
tensor2 = torch.tensor(([0, 1, 7], [4, 2, 4]))

In [7]:
# Dimension and shape of a tensor
print(f'Vector:\n {tensor1}\t No. of dimensions: {tensor1.ndim}\t Shape: {tensor1.shape}\n')
print(f'Matrix:\n {tensor2}\t No. of dimensions: {tensor2.ndim}\t Shape: {tensor2.size()}\n')

Vector:
 tensor([6, 8, 0, 1, 2])	 No. of dimensions: 1	 Shape: torch.Size([5])

Matrix:
 tensor([[0, 1, 7],
        [4, 2, 4]])	 No. of dimensions: 2	 Shape: torch.Size([2, 3])



In [8]:
# Alternate ways
size = (3, 4)
tensor4 = torch.empty(size)
tensor4

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [9]:
tensor5 = torch.rand(size)
tensor5

tensor([[0.2255, 0.3157, 0.1492, 0.0913],
        [0.7037, 0.4802, 0.8967, 0.3572],
        [0.3597, 0.3768, 0.1483, 0.3396]])

In [10]:
tensor6 = torch.zeros(size)
tensor6

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [11]:
tensor7 = torch.ones(size)
tensor7

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [12]:
# Check the datatype of a tensor
tensor4 = torch.rand(1,2)
print(tensor4)
tensor4.dtype

tensor([[0.5062, 0.9484]])


torch.float32

In [13]:
# Create a tensor with a specific datatype
tensor5 = torch.rand(1, 2, dtype = torch.float16)
print(tensor5)

tensor([[0.2524, 0.3389]], dtype=torch.float16)


In [14]:
# Changing the datatype of a tensor
tensor4.type(torch.double)

tensor([[0.5062, 0.9484]], dtype=torch.float64)

In [15]:
# Creating tensors from a numpy array
import numpy as np

example_array = np.array([[9, 3], [0, 4]])
tensor8 =torch.from_numpy(example_array)

tensor9 = torch.tensor(example_array)
print(example_array)
print(tensor8)
print(tensor9)

[[9 3]
 [0 4]]
tensor([[9, 3],
        [0, 4]], dtype=torch.int32)
tensor([[9, 3],
        [0, 4]], dtype=torch.int32)


In [16]:
example_array*= 3
print(example_array)
print(tensor8)
print(tensor9)

[[27  9]
 [ 0 12]]
tensor([[27,  9],
        [ 0, 12]], dtype=torch.int32)
tensor([[9, 3],
        [0, 4]], dtype=torch.int32)


In [17]:
# Crearing a tensor from another tensor

tensor10 = torch.ones_like(tensor8)
tensor10

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)

In [18]:
# Device configuration

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

tensor11 = torch.ones(3, 7).to(device)

tensor11 = torch.zeros(3, 7, device = device)

## 2. Accessing elements in a tensor

In [19]:
tensor2

tensor([[0, 1, 7],
        [4, 2, 4]])

In [20]:
tensor2.dim()

2

In [21]:
tensor2.size()

torch.Size([2, 3])

In [22]:
tensor2[0]

tensor([0, 1, 7])

In [23]:
tensor2[1, 0]

tensor(4)

In [24]:
# Slicing
tensor2[:, 2] # this will guive us all the rows and only column 2

tensor([7, 4])

In [25]:
tensor2[0, :] # this will give us only row 0 along with all columns 

tensor([0, 1, 7])

## 3. Basic Tensor Operations

In [26]:
tensor12 = torch.ones(2, 3)
tensor13 = torch.rand(2, 3)

print(tensor12)
print(tensor13)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.5942, 0.2187, 0.2556],
        [0.4682, 0.1268, 0.8165]])


In [27]:
# Elementwise addition
tensor14 = tensor12 + tensor13
# torch.add(tensor12, tensor13)
print(tensor14)

# Elementwise subtraction
tensor15 = tensor12 - tensor13
# torch.sub(tensor12, tensor13)
print(tensor15)

# Elementwise multiplication
tensor16 = tensor12 * tensor13
# torch.mul(tensor12, tensor13)
print(tensor16)

# Elementwise division
tensor17 = tensor12 / tensor12
# torch.div(tensor12, tensor13)
print(tensor17)

tensor([[1.5942, 1.2187, 1.2556],
        [1.4682, 1.1268, 1.8165]])
tensor([[0.4058, 0.7813, 0.7444],
        [0.5318, 0.8732, 0.1835]])
tensor([[0.5942, 0.2187, 0.2556],
        [0.4682, 0.1268, 0.8165]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


## 4. Manipulating a Tensor

In [28]:
x = torch.randint(0, 3, (4, 5))
x

tensor([[0, 2, 2, 2, 1],
        [0, 0, 2, 1, 1],
        [0, 0, 1, 1, 2],
        [1, 1, 0, 1, 1]])

In [29]:
y = x.view(20)
z = x.view(-1, 10)

In [30]:
print(x.size(), y.size(), z.size())

torch.Size([4, 5]) torch.Size([20]) torch.Size([2, 10])


In [31]:
a = torch.arange(9)
a = a.reshape(3, 3)
a

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [32]:
b = torch.randint(0, 9, (3, 3)) ## torch.randint(low = 0, high, size)
b

tensor([[4, 7, 6],
        [6, 5, 6],
        [3, 2, 6]])

In [33]:
c = torch.cat((a, b), dim = 1)
c

tensor([[0, 1, 2, 4, 7, 6],
        [3, 4, 5, 6, 5, 6],
        [6, 7, 8, 3, 2, 6]])

In [34]:
d = torch.cat((a, b), dim = 0)
d

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8],
        [4, 7, 6],
        [6, 5, 6],
        [3, 2, 6]])

In [35]:
a

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [36]:
p = torch.randint(0, 9, (2, 3, 5))
p

tensor([[[0, 8, 4, 5, 1],
         [3, 1, 1, 1, 6],
         [8, 5, 0, 3, 7]],

        [[5, 2, 4, 7, 1],
         [8, 3, 6, 7, 0],
         [5, 8, 3, 0, 4]]])

In [37]:
p.sum()

tensor(116)

In [38]:
p.sum(dim = 0)

tensor([[ 5, 10,  8, 12,  2],
        [11,  4,  7,  8,  6],
        [13, 13,  3,  3, 11]])

In [39]:
p.sum(dim= 1)

tensor([[11, 14,  5,  9, 14],
        [18, 13, 13, 14,  5]])

In [40]:
p.sum(dim = 1).shape

torch.Size([2, 5])

# Autograd

In [41]:
import torch 

x = torch.tensor(2.0)
x.requires_grad, x.is_leaf

(False, True)

In [42]:
y = 3 * torch.sigmoid(x) + 5
y.requires_grad, y.is_leaf

(False, True)

In [43]:
import torch

x = torch.tensor(2.0, requires_grad = True)

x.requires_grad, x.is_leaf

(True, True)

In [44]:
y = 3 * torch.sigmoid(x) + 5
y

tensor(7.6424, grad_fn=<AddBackward0>)

In [45]:
y.requires_grad, y.is_leaf

(True, False)

In [46]:
print(x.grad_fn)

None


In [47]:
print(y.grad_fn)

In [48]:
print(x.grad)
y.backward()
print(x.grad) #dy/dx

None
tensor(0.3150)


In [49]:
# x.grad.zero_()
y = 3 * torch.sigmoid(x) + 5
y.backward()
x.grad

tensor(0.6300)

In [50]:
a = torch.rand(2, 5, requires_grad = True)
a

tensor([[0.4221, 0.0027, 0.7350, 0.6434, 0.1180],
        [0.6999, 0.5469, 0.5512, 0.4673, 0.4156]], requires_grad=True)

In [51]:
b = a * a + a + 5
b

tensor([[5.6002, 5.0027, 6.2753, 6.0574, 5.1320],
        [6.1898, 5.8461, 5.8549, 5.6858, 5.5884]], grad_fn=<AddBackward0>)

In [52]:
c = b.mean()
c

tensor(5.7232, grad_fn=<MeanBackward0>)

In [53]:
a.is_leaf, b.is_leaf, c.is_leaf

(True, False, False)

In [54]:
b.retain_grad()

In [55]:
print(a.grad) # Before gradient computation
c.backward()
print(a.grad) # After gradient computation dc/da

None
tensor([[0.1844, 0.1005, 0.2470, 0.2287, 0.1236],
        [0.2400, 0.2094, 0.2102, 0.1935, 0.1831]])


In [56]:
b.grad

tensor([[0.1000, 0.1000, 0.1000, 0.1000, 0.1000],
        [0.1000, 0.1000, 0.1000, 0.1000, 0.1000]])

# Gradient Descent

In [57]:
# Generate train data # y = 5 * x + 3
x = torch.linspace(0.0, 1.0, 15).reshape(15, 1)
w = torch.tensor([5])
b = torch.tensor([3])
y = w * x + b


In [58]:
# Parameter Initialization
w = torch.randn(size = (1, 1), requires_grad = True)
b = torch.randn(size = (1, 1), requires_grad = True)

def forward(x):
    return w * x + b

def loss(y, y_pred):
    return ((y_pred - y) ** 2).mean()

print('w: ', w)
print('b: ', b)

w:  tensor([[-0.3274]], requires_grad=True)
b:  tensor([[-0.8969]], requires_grad=True)


In [59]:
# Define hyper-parameters
learning_rate = 0.03
num_epochs = 180

#Train the model
for epoch in range(num_epochs):
    y_pred = forward(x)
    
    l = loss(y, y_pred)
    l.backward()
    
    with torch.no_grad():
        w -= learning_rate * w.grad
        b -= learning_rate * b.grad
        
    w.grad.zero_()
    b.grad.zero_()
    
    if (epoch + 1) % 10 == 0:
        print(f'epoch {epoch + 1}: w = {w.item() :.3f}, b = {b.item():.3f}, loss = {l.item():.3f}')

epoch 10: w = 1.334, b = 1.914, loss = 11.391
epoch 20: w = 2.142, b = 3.157, loss = 2.727
epoch 30: w = 2.560, b = 3.691, loss = 0.918
epoch 40: w = 2.800, b = 3.905, loss = 0.517
epoch 50: w = 2.957, b = 3.976, loss = 0.406
epoch 60: w = 3.074, b = 3.983, loss = 0.358
epoch 70: w = 3.171, b = 3.962, loss = 0.324
epoch 80: w = 3.257, b = 3.930, loss = 0.295
epoch 90: w = 3.336, b = 3.894, loss = 0.270
epoch 100: w = 3.411, b = 3.856, loss = 0.247
epoch 110: w = 3.482, b = 3.820, loss = 0.225
epoch 120: w = 3.549, b = 3.784, loss = 0.206
epoch 130: w = 3.613, b = 3.750, loss = 0.188
epoch 140: w = 3.674, b = 3.717, loss = 0.172
epoch 150: w = 3.732, b = 3.685, loss = 0.157
epoch 160: w = 3.788, b = 3.655, loss = 0.144
epoch 170: w = 3.842, b = 3.626, loss = 0.131
epoch 180: w = 3.893, b = 3.598, loss = 0.120


# Neural Networks

In [60]:
import torch
import torch.nn as nn
# import torch.nn.functional as F
import torch.optim as optim

from torchvision import datasets, transforms

In [61]:
print(dir(datasets))

['CIFAR10', 'CIFAR100', 'CLEVRClassification', 'CREStereo', 'Caltech101', 'Caltech256', 'CarlaStereo', 'CelebA', 'Cityscapes', 'CocoCaptions', 'CocoDetection', 'Country211', 'DTD', 'DatasetFolder', 'EMNIST', 'ETH3DStereo', 'EuroSAT', 'FER2013', 'FGVCAircraft', 'FakeData', 'FallingThingsStereo', 'FashionMNIST', 'Flickr30k', 'Flickr8k', 'Flowers102', 'FlyingChairs', 'FlyingThings3D', 'Food101', 'GTSRB', 'HD1K', 'HMDB51', 'INaturalist', 'ImageFolder', 'ImageNet', 'Imagenette', 'InStereo2k', 'KMNIST', 'Kinetics', 'Kitti', 'Kitti2012Stereo', 'Kitti2015Stereo', 'KittiFlow', 'LFWPairs', 'LFWPeople', 'LSUN', 'LSUNClass', 'MNIST', 'Middlebury2014Stereo', 'MovingMNIST', 'Omniglot', 'OxfordIIITPet', 'PCAM', 'PhotoTour', 'Places365', 'QMNIST', 'RenderedSST2', 'SBDataset', 'SBU', 'SEMEION', 'STL10', 'SUN397', 'SVHN', 'SceneFlowStereo', 'Sintel', 'SintelStereo', 'StanfordCars', 'UCF101', 'USPS', 'VOCDetection', 'VOCSegmentation', 'VisionDataset', 'WIDERFace', '__all__', '__builtins__', '__cached__',

In [62]:
# Hyper-parameters
hidden_size = 400
num_epochs = 8
batch_size = 32
learning_rate = 0.0001

In [63]:
# Load the MNIST dataset
train_dataset = datasets.MNIST(root = './data', train = True, download = True, transform = transforms.ToTensor())
test_dataset = datasets.MNIST(root = './data',train = False, download = True, transform = transforms.ToTensor())

In [64]:
# Training Data
print(train_dataset.classes)
print(train_dataset.data.shape)
print(train_dataset.targets.shape)

['0 - zero', '1 - one', '2 - two', '3 - three', '4 - four', '5 - five', '6 - six', '7 - seven', '8 - eight', '9 - nine']
torch.Size([60000, 28, 28])
torch.Size([60000])


In [65]:
# Test Data
print(test_dataset.classes)
print(test_dataset.data.shape)
print(test_dataset.targets.shape)

['0 - zero', '1 - one', '2 - two', '3 - three', '4 - four', '5 - five', '6 - six', '7 - seven', '8 - eight', '9 - nine']
torch.Size([10000, 28, 28])
torch.Size([10000])


In [66]:
in_features = 784 # Input size = 28 * 28
out_features = 10 # no. of classes

In [67]:
train_dataloader = torch.utils.data.DataLoader(dataset = train_dataset, batch_size = batch_size, shuffle = True)
test_dataloader = torch.utils.data.DataLoader(dataset = test_dataset, batch_size = batch_size, shuffle = False)

In [ ]:
import matplotlib.pyplot as plt

data = iter(train_dataloader)
imgs, labels = next(data)
print(imgs.shape)
print(labels.shape)

for i in range(5):
    plt.subplot(1, 5, i + 1)
    plt.imshow(imgs[i][0], cmap = 'gray')
    plt.xlabel(f'Label = {labels[i].item()}')
plt.show()

torch.Size([32, 1, 28, 28])
torch.Size([32])
