In [1]:
import torch

In [2]:
torch.__version__

'2.5.1+cpu'

# Tensors

## 1. Creating Tensors

In [3]:
# scalar - tensor with zero dimension
tensor0 = torch.tensor(1)
tensor0

tensor(1)

In [4]:
tensor0.ndim

0

In [5]:
# vector - tensor with one dimension
tensor1 = torch.tensor([6, 8, 0, 1, 2])

In [6]:
# matrix - tensor with two dimensions
tensor2 = torch.tensor(([0, 1, 7], [4, 2, 4]))

In [7]:
# Dimension and shape of a tensor
print(f'Vector:\n {tensor1}\t No. of dimensions: {tensor1.ndim}\t Shape: {tensor1.shape}\n')
print(f'Matrix:\n {tensor2}\t No. of dimensions: {tensor2.ndim}\t Shape: {tensor2.size()}\n')

Vector:
 tensor([6, 8, 0, 1, 2])	 No. of dimensions: 1	 Shape: torch.Size([5])

Matrix:
 tensor([[0, 1, 7],
        [4, 2, 4]])	 No. of dimensions: 2	 Shape: torch.Size([2, 3])



In [8]:
# Alternate ways
size = (3, 4)
tensor4 = torch.empty(size)
tensor4

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [9]:
tensor5 = torch.rand(size)
tensor5

tensor([[0.7723, 0.5631, 0.7896, 0.3057],
        [0.0615, 0.2882, 0.9314, 0.4881],
        [0.6888, 0.3305, 0.7805, 0.0052]])

In [10]:
tensor6 = torch.zeros(size)
tensor6

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [11]:
tensor7 = torch.ones(size)
tensor7

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [12]:
# Check the datatype of a tensor
tensor4 = torch.rand(1,2)
print(tensor4)
tensor4.dtype

tensor([[0.6573, 0.5059]])


torch.float32

In [13]:
# Create a tensor with a specific datatype
tensor5 = torch.rand(1, 2, dtype = torch.float16)
print(tensor5)

tensor([[0.0430, 0.4038]], dtype=torch.float16)


In [14]:
# Changing the datatype of a tensor
tensor4.type(torch.double)

tensor([[0.6573, 0.5059]], dtype=torch.float64)

In [16]:
# Creating tensors from a numpy array
import numpy as np

example_array = np.array([[9, 3], [0, 4]])
tensor8 =torch.from_numpy(example_array)

tensor9 = torch.tensor(example_array)
print(example_array)
print(tensor8)
print(tensor9)

[[9 3]
 [0 4]]
tensor([[9, 3],
        [0, 4]], dtype=torch.int32)
tensor([[9, 3],
        [0, 4]], dtype=torch.int32)


In [17]:
example_array*= 3
print(example_array)
print(tensor8)
print(tensor9)

[[27  9]
 [ 0 12]]
tensor([[27,  9],
        [ 0, 12]], dtype=torch.int32)
tensor([[9, 3],
        [0, 4]], dtype=torch.int32)


In [18]:
# Crearing a tensor from another tensor

tensor10 = torch.ones_like(tensor8)
tensor10

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)

In [19]:
# Device configuration

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

tensor11 = torch.ones(3, 7).to(device)

tensor11 = torch.zeros(3, 7, device = device)

## 2. Accessing elements in a tensor

In [20]:
tensor2

tensor([[0, 1, 7],
        [4, 2, 4]])

In [21]:
tensor2.dim()

2

In [22]:
tensor2.size()

torch.Size([2, 3])

In [23]:
tensor2[0]

tensor([0, 1, 7])

In [24]:
tensor2[1, 0]

tensor(4)

In [25]:
# Slicing
tensor2[:, 2] # this will guive us all the rows and only column 2

tensor([7, 4])

In [26]:
tensor2[0, :] # this will give us only row 0 along with all columns 

tensor([0, 1, 7])

## 3. Basic Tensor Operations

In [28]:
tensor12 = torch.ones(2, 3)
tensor13 = torch.rand(2, 3)

print(tensor12)
print(tensor13)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.3801, 0.9971, 0.4550],
        [0.3314, 0.6067, 0.0866]])


In [31]:
# Elementwise addition
tensor14 = tensor12 + tensor13
# torch.add(tensor12, tensor13)
print(tensor14)

# Elementwise subtraction
tensor15 = tensor12 - tensor13
# torch.sub(tensor12, tensor13)
print(tensor15)

# Elementwise multiplication
tensor16 = tensor12 * tensor13
# torch.mul(tensor12, tensor13)
print(tensor16)

# Elementwise division
tensor17 = tensor12 / tensor12
# torch.div(tensor12, tensor13)
print(tensor17)

tensor([[1.3801, 1.9971, 1.4550],
        [1.3314, 1.6067, 1.0866]])
tensor([[0.6199, 0.0029, 0.5450],
        [0.6686, 0.3933, 0.9134]])
tensor([[0.3801, 0.9971, 0.4550],
        [0.3314, 0.6067, 0.0866]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


## 4. Manipulating a Tensor

In [32]:
x = torch.randint(0, 3, (4, 5))
x

tensor([[0, 2, 1, 2, 0],
        [0, 1, 0, 0, 2],
        [1, 0, 0, 1, 0],
        [2, 1, 0, 0, 2]])

In [33]:
y = x.view(20)
z = x.view(-1, 10)

In [34]:
print(x.size(), y.size(), z.size())

torch.Size([4, 5]) torch.Size([20]) torch.Size([2, 10])


In [36]:
a = torch.arange(9)
a = a.reshape(3, 3)
a

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])