In [1]:
import torch

In [2]:
torch.__version__

'2.5.1+cpu'

# Tensors

## 1. Creating Tensors

In [3]:
# scalar - tensor with zero dimension
tensor0 = torch.tensor(1)
tensor0

tensor(1)

In [4]:
tensor0.ndim

0

In [5]:
# vector - tensor with one dimension
tensor1 = torch.tensor([6, 8, 0, 1, 2])

In [8]:
# matrix - tensor with two dimensions
tensor2 = torch.tensor(([0, 1, 7], [4, 2, 4]))

In [12]:
# Dimension and shape of a tensor
print(f'Vector:\n {tensor1}\t No. of dimensions: {tensor1.ndim}\t Shape: {tensor1.shape}\n')
print(f'Matrix:\n {tensor2}\t No. of dimensions: {tensor2.ndim}\t Shape: {tensor2.size()}\n')

Vector:
 tensor([6, 8, 0, 1, 2])	 No. of dimensions: 1	 Shape: torch.Size([5])

Matrix:
 tensor([[0, 1, 7],
        [4, 2, 4]])	 No. of dimensions: 2	 Shape: torch.Size([2, 3])



In [13]:
# Alternate ways
size = (3, 4)
tensor4 = torch.empty(size)
tensor4

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [14]:
tensor5 = torch.rand(size)
tensor5

tensor([[0.6566, 0.2143, 0.1542, 0.1527],
        [0.1519, 0.8658, 0.8459, 0.3045],
        [0.0357, 0.3297, 0.1793, 0.6006]])

In [16]:
tensor6 = torch.zeros(size)
tensor6

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [17]:
tensor7 = torch.ones(size)
tensor7

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [20]:
# Check the datatype of a tensor
tensor4 = torch.rand(1,2)
print(tensor4)
tensor4.dtype

tensor([[0.1297, 0.8199]])


torch.float32

In [22]:
# Create a tensor with a specific datatype
tensor5 = torch.rand(1, 2, dtype = torch.float16)
print(tensor5)

tensor([[0.5029, 0.7515]], dtype=torch.float16)


In [23]:
# Changing the datatype of a tensor
tensor4.type(torch.double)

tensor([[0.1297, 0.8199]], dtype=torch.float64)

In [24]:
# Creating tensors from a numpy array
import numpy as np

example_array = np.array([[9, 3], [0, 4]])
tensor8 =torch.from_numpy(example_array)

tensor9 = torch.tensor(example_array)
print(example_arr)
